name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.2

      - name: Terraform Init
        env:
          ARM_CLIENT_ID: 'ace61daa-7e98-4d1c-8dc6-c3d2d1537891'
          ARM_CLIENT_SECRET: 'Sep8Q~iOExmed_AjdhrKU5Ghg_-434MAG.50Hbkn'
          ARM_SUBSCRIPTION_ID: '1e437fdf-bd78-431d-ba95-1498f0e84c10'
          ARM_TENANT_ID: '35db3582-96af-4081-a32c-7bbaa2cf3ca9'
         
        run: terraform init


      - name: Terraform Plan
        env:
          ARM_CLIENT_ID: 'ace61daa-7e98-4d1c-8dc6-c3d2d1537891'
          ARM_CLIENT_SECRET: 'Sep8Q~iOExmed_AjdhrKU5Ghg_-434MAG.50Hbkn'
          ARM_SUBSCRIPTION_ID: '1e437fdf-bd78-431d-ba95-1498f0e84c10'
          ARM_TENANT_ID: '35db3582-96af-4081-a32c-7bbaa2cf3ca9'
        
        run: terraform plan -input=false -var="location=Canada Central" -var="resource_group_name=TESTRG_GA" -var="name=TESTVNET-GA" -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push'
        env:
          ARM_CLIENT_ID: 'ace61daa-7e98-4d1c-8dc6-c3d2d1537891'
          ARM_CLIENT_SECRET: 'Sep8Q~iOExmed_AjdhrKU5Ghg_-434MAG.50Hbkn'
          ARM_SUBSCRIPTION_ID: '1e437fdf-bd78-431d-ba95-1498f0e84c10'
          ARM_TENANT_ID: '35db3582-96af-4081-a32c-7bbaa2cf3ca9'
        run: terraform apply -auto-approve tfplan
