jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          terraform_version: '1.6.0'   # Adjust the version to match your required version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
